### ISSUE TITLE
Editext of IP.

### ISSUE THREAD

**Issue by doomers** [doomers/Remote-Desktop#3]
currently, IP is hard-coded in the constants file.
make a editext where user can enter the IP of his system.'

Feel free to ask anything about this issue in comments.

**Comment by mohamed-habib** [comment]
Working on it on the android app....

**Comment by arpitbatra123** [comment]
I'd like to work on this issue.

**Comment by doomers** [comment]
@shollifield has already done it.
@arpitbatra123  you can work on other issues.
